baseURL = "https://www.sinmat.my.id"
title = "Sinau Matematika"

# untuk apply temanya
themesDir = "themes"
theme = "temaku"
copyright = "Â© {year} | Sinau Matematika"

# Multilingual mode
defaultContentLanguage = "id"

# Pagination
paginate = 6
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

# hasCJKLanguage = true # Turn on it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["json"]
  
[outputFormats]
  [outputFormats.MANIFEST]
    name = "manifest"
    baseName = "manifest"
    mediaType = "application/manifest+json"

[outputs]
  home = ["HTML", "RSS", "JSON", "MANIFEST"]

[taxonomies]
  categories = "categories"
  series = "series"
  tags = "tags"
  topik = "topik"
  seri = "seri"
  kategori = "kategori"

[permalinks]
  post = '/:filename'
  categories ='/:slug'
  belajar='/:slug'
  tutorial='/:slug'
  mat-sma='/:slug'